import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { z } from 'zod';
import { 
  FileText, DollarSign, Clock, ListChecks, 
  Sparkles, CheckCircle2, Trash2, Plus
} from 'lucide-react';
import { Button } from '@/shared/components/ui/Button';
import { Input } from '@/shared/components/ui/Input';
import { cn } from '@/lib/utils';
import type { AiJobSuggestion, SuggestedMilestone } from '../types';
import { BudgetType } from '@/shared/types/enums';

const jobDraftSchema = z.object({
  title: z.string().min(5, 'Title must be at least 5 characters'),
  description: z.string().min(20, 'Description must be at least 20 characters').max(5000, 'Description is too long'),
  budgetType: z.nativeEnum(BudgetType),
  budgetMin: z.number().min(1, 'Minimum budget must be at least 1'),
  budgetMax: z.number().min(1, 'Maximum budget must be at least 1'),
  timelineDays: z.number().min(1, 'Timeline must be at least 1 day'),
});

type JobDraftFormValues = z.infer<typeof jobDraftSchema>;

interface JobDraftFormProps {
  suggestion: AiJobSuggestion;
  onUpdate: (data: Partial<AiJobSuggestion>) => void;
  onAccept: () => void;
  onSaveDraft: () => void;
  isAccepting: boolean;
}

export const JobDraftForm = ({ 
  suggestion, 
  onUpdate, 
  onAccept,
  onSaveDraft,
  isAccepting 
}: JobDraftFormProps) => {
  const { register, handleSubmit, setValue, formState: { errors } } = useForm<JobDraftFormValues>({
    resolver: zodResolver(jobDraftSchema),
    values: {
      title: suggestion.suggestedTitle,
      description: suggestion.suggestedDescription,
      budgetType: suggestion.budgetType,
      budgetMin: suggestion.suggestedBudgetMin ?? ('' as unknown as number),
      budgetMax: suggestion.suggestedBudgetMax ?? ('' as unknown as number),
      timelineDays: suggestion.suggestedTimelineDays ?? ('' as unknown as number),
    }
  });

  const onSubmit = (data: JobDraftFormValues) => {
    onUpdate({
      suggestedTitle: data.title,
      suggestedDescription: data.description,
      budgetType: data.budgetType,
      suggestedBudgetMin: data.budgetMin,
      suggestedBudgetMax: data.budgetMax,
      suggestedTimelineDays: data.timelineDays,
    });
  };

  const handleRemoveMilestone = (index: number) => {
    const newMilestones = suggestion.suggestedMilestones.filter((_, i) => i !== index);
    onUpdate({ suggestedMilestones: newMilestones });
  };

  const handleAddMilestone = () => {
    const newMilestone: SuggestedMilestone = {
      title: 'New Milestone',
      description: '',
      amount: 0,
      dueDays: 0,
      orderIndex: suggestion.suggestedMilestones.length
    };
    onUpdate({ suggestedMilestones: [...suggestion.suggestedMilestones, newMilestone] });
  };

  return (
    <div className="flex flex-col min-h-full bg-white border border-slate-100 rounded-3xl shadow-sm overflow-hidden">
      {/* Header */}
      <div className="p-6 bg-slate-50 border-b border-slate-100 flex items-center justify-between">
        <div className="flex items-center gap-3">
          <div className="size-10 rounded-xl bg-blue-100 flex items-center justify-center border border-blue-200">
            <FileText className="size-5 text-primary" />
          </div>
          <div>
            <h3 className="text-base font-black text-slate-900 leading-none text-left">Project Draft</h3>
            <p className="text-xs font-bold text-slate-400 uppercase tracking-widest mt-1 text-left">Generated by AI</p>
          </div>
        </div>
        <div className="flex items-center gap-2">
           <div className="flex items-center gap-1 px-3 py-1 bg-emerald-50 rounded-full border border-emerald-100">
              <CheckCircle2 className="size-3 text-emerald-600" />
              <span className="text-[10px] font-black text-emerald-700 uppercase tracking-widest">Draft Ready</span>
           </div>
        </div>
      </div>

      {/* Form Area */}
      <div className="flex-1 min-h-0 overflow-y-auto p-8 space-y-10 custom-scrollbar">
        <form id="job-draft-form" onSubmit={handleSubmit(onSubmit)} className="space-y-8">
          
          {/* Section: Basic Info */}
          <div className="space-y-6 text-left">
            <div className="flex items-center gap-2 text-primary">
              <Sparkles className="size-4" />
              <h4 className="text-xs font-black uppercase tracking-widest">Essential Information</h4>
            </div>

            <div className="space-y-2">
              <label className="text-xs font-bold text-slate-500 ml-1 uppercase">Job Title</label>
              <Input 
                {...register('title')} 
                placeholder="Job Title"
                className="h-12 rounded-xl bg-slate-50 border-slate-100 focus:bg-white text-base font-bold text-slate-900" 
              />
              {errors.title && <p className="text-xs text-rose-500 font-bold ml-1">{errors.title.message}</p>}
            </div>

            <div className="space-y-2">
              <label className="text-xs font-bold text-slate-500 ml-1 uppercase">Project Description</label>
              <textarea 
                {...register('description')}
                rows={6}
                className="w-full p-4 rounded-xl bg-slate-50 border border-slate-100 focus:bg-white focus:outline-none focus:ring-4 focus:ring-primary/5 transition-all text-sm leading-relaxed text-slate-700"
              />
              {errors.description && <p className="text-xs text-rose-500 font-bold ml-1">{errors.description.message}</p>}
            </div>
          </div>

          {/* Section: Budget & Timeline */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-8 text-left">
            <div className="space-y-6">
              <div className="flex items-center gap-2 text-primary text-left">
                <DollarSign className="size-4" />
                <h4 className="text-xs font-black uppercase tracking-widest text-left">Budget Estimate</h4>
              </div>
              <div className="space-y-4">
                 <div className="flex gap-4">
                    <div className="flex-1 space-y-2">
                       <label className="text-[10px] font-bold text-slate-400 uppercase ml-1">Min ({suggestion.currency || 'Xu'})</label>
                       <Input type="number" {...register('budgetMin', { valueAsNumber: true })} className="h-11 rounded-xl bg-slate-50" />
                    </div>
                    <div className="flex-1 space-y-2">
                       <label className="text-[10px] font-bold text-slate-400 uppercase ml-1">Max ({suggestion.currency || 'Xu'})</label>
                       <Input type="number" {...register('budgetMax', { valueAsNumber: true })} className="h-11 rounded-xl bg-slate-50" />
                       {errors.budgetMax && <p className="text-xs text-rose-500 font-bold ml-1">{errors.budgetMax.message}</p>}
                    </div>
                 </div>
                 <div className="flex bg-slate-50 p-1 rounded-xl border border-slate-100">
                    <button 
                      type="button"
                      onClick={() => {
                        setValue('budgetType', BudgetType.FIXED);
                        onUpdate({ budgetType: BudgetType.FIXED });
                      }}
                      className={cn(
                        "flex-1 py-2 text-xs font-bold rounded-lg transition-all",
                        suggestion.budgetType === BudgetType.FIXED ? "bg-white shadow-sm text-primary" : "text-slate-500 hover:text-slate-700"
                      )}
                    >Fixed Price</button>
                    <button 
                      type="button"
                      onClick={() => {
                        setValue('budgetType', BudgetType.HOURLY);
                        onUpdate({ budgetType: BudgetType.HOURLY });
                      }}
                      className={cn(
                        "flex-1 py-2 text-xs font-bold rounded-lg transition-all",
                        suggestion.budgetType === BudgetType.HOURLY ? "bg-white shadow-sm text-primary" : "text-slate-500 hover:text-slate-700"
                      )}
                    >Hourly Rate</button>
                 </div>
              </div>
            </div>

            <div className="space-y-6">
              <div className="flex items-center gap-2 text-primary">
                <Clock className="size-4" />
                <h4 className="text-xs font-black uppercase tracking-widest text-left">Target Timeline</h4>
              </div>
              <div className="space-y-2">
                <label className="text-[10px] font-bold text-slate-400 uppercase ml-1">Days to Complete</label>
                <Input type="number" {...register('timelineDays', { valueAsNumber: true })} className="h-11 rounded-xl bg-slate-50" />
              </div>
            </div>
          </div>

          {/* Section: Milestones */}
          <div className="space-y-6 text-left">
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-2 text-primary">
                <ListChecks className="size-4" />
                <h4 className="text-xs font-black uppercase tracking-widest text-left">Suggested Milestones</h4>
              </div>
              <Button type="button" onClick={handleAddMilestone} variant="ghost" size="sm" className="h-8 rounded-lg text-primary text-xs font-bold gap-1">
                 <Plus className="size-3" /> Add Milestone
              </Button>
            </div>

            <div className="space-y-3">
              {suggestion.suggestedMilestones.map((ms, idx) => (
                <div key={ms.id || `milestone-${idx}-${ms.title}`} className="p-4 bg-slate-50 border border-slate-100 rounded-2xl flex items-start justify-between gap-4 group">
                  <div className="flex items-start gap-4">
                    <div className="size-8 rounded-lg bg-white border border-slate-200 flex items-center justify-center shrink-0 font-black text-xs text-slate-400">
                      {idx + 1}
                    </div>
                    <div className="text-left">
                      <p className="text-sm font-bold text-slate-900">{ms.title}</p>
                      <p className="text-xs text-slate-500 line-clamp-1 mt-1 font-medium">{ms.description}</p>
                    </div>
                  </div>
                  <div className="flex items-center gap-4">
                     <span className="text-xs font-black text-slate-700">{ms.amount ?? 0}%</span>
                     <button 
                       type="button" 
                       onClick={() => handleRemoveMilestone(idx)}
                       className="opacity-0 group-hover:opacity-100 transition-opacity p-1 text-slate-300 hover:text-rose-500"
                       aria-label="Remove milestone"
                     >
                        <Trash2 className="size-4" />
                     </button>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </form>
      </div>

      {/* Footer Actions */}
      <div className="p-6 bg-white border-t border-slate-100 flex items-center justify-between gap-4">
         <div className="hidden sm:block">
            <p className="text-[10px] font-bold text-slate-400 uppercase tracking-widest">Final Step</p>
            <p className="text-xs font-black text-slate-900 mt-1">Review & Publish</p>
         </div>
         <div className="flex items-center gap-3 w-full sm:w-auto">
            <Button 
              variant="outline" 
              className="flex-1 sm:flex-none rounded-full font-bold border-slate-200"
              onClick={onSaveDraft}
            >
              Save Draft
            </Button>
            <Button 
              onClick={onAccept}
              disabled={isAccepting}
              className="flex-[2] sm:flex-none rounded-full px-10 font-black shadow-xl shadow-primary/20 bg-primary hover:scale-[1.02] active:scale-95 transition-all"
            >
              {isAccepting ? 'Publishing...' : 'Publish Project'}
            </Button>
         </div>
      </div>
    </div>
  );
};
